### PR TITLE
updating jdks to state as for 25/2 2022 22:00 CET

### PR DESCRIPTION
**Pull request by judovana**

### CODE REVIEW

**Comment by tellison** [comment]
Thanks @judovana - waiting for the validation tests to run. Should be less than 10 mins

**Review by tellison — APPROVED** [review]
Binary download links checked

**Comment by judovana** [comment]
That was all?? :D I expect half of it wrong...

**Comment by tellison** [comment]
Well it is all valid, just checking on the staging server now (which requires this PR is landed).

**Pull request merged**
