### PR TITLE
Add July 2022 security updates (8u342, 11.0.16, 17.0.4)

### PR DESCRIPTION
**Pull request by gnu-andrew**
Improve failure reporting in verification script.

### CODE REVIEW

**Comment by tellison** [comment]
Failed Adoptium's validation with
```
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.util.Date` from String "2022-07-20T18:39-04:00": expected format "yyyy-MM-dd'T'HH:mm:ssXXX"
```

Please update to use a parseable format throughout, such as used here:
`"last_updated_timestamp": "2022-07-21T12:05:00Z"`

**Comment by judovana** [comment]
Hi Andrew!
I had fixed the genrator and updated jsons in auto release folder. Feel free to check/use.

**Comment by gnu-andrew** [comment]
> Failed Adoptium's validation with
> 
> ```
> com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.util.Date` from String "2022-07-20T18:39-04:00": expected format "yyyy-MM-dd'T'HH:mm:ssXXX"
> ```
> 
> Please update to use a parseable format throughout, such as used here: `"last_updated_timestamp": "2022-07-21T12:05:00Z"`

Yeah, I already corrected a few.  The initial JSON was created by a script from @judovana but it seems to be producing invalid timestamps. Correcting the rest now.

**Comment by gnu-andrew** [comment]
> Hi Andrew! I had fixed the genrator and updated jsons in auto release folder. Feel free to check/use.

They still aren't correct there:
~~~
$ ~/build/icedtea8/bin/java TestTimestamp 2022-07-22T11:39-04:00Z
FAILURE: Exception java.time.format.DateTimeParseException: Text '2022-07-22T11:39-04:00Z' could not be parsed at index 16 when parsing 2022-07-22T11:39-04:00Z
1 timestamp failures
~~~

Is the generator maintained somewhere I can submit a PR? There were other issues that needed manual change too

**Comment by gnu-andrew** [comment]
FWIW, that one should be:
~~~
$ date -u +%Y-%m-%dT%H:%M:%SZ --date=2022-07-22T11:39-04:00
2022-07-22T15:39:00Z
~~~

**Comment by gnu-andrew** [comment]
Going to merge this as checks have passed.

**Comment by judovana** [comment]
> > Failed Adoptium's validation with
> > ```
> > com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.util.Date` from String "2022-07-20T18:39-04:00": expected format "yyyy-MM-dd'T'HH:mm:ssXXX"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please update to use a parseable format throughout, such as used here: `"last_updated_timestamp": "2022-07-21T12:05:00Z"`
> 
> Yeah, I already corrected a few. The initial JSON was created by a script from @judovana but it seems to be producing invalid timestamps. Correcting the rest now.

Hello! Pls let me know all issues yo have to fix manually, so I ca finish any missing tuning the generator had

**Pull request merged**
